apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mas
  namespace: mas-max-core
spec:
  channel: 9.2.x-feature 
  installPlanApproval: Automatic
  name: ibm-mas
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-mas.v9.2.0-pre.stable-9887
  config:
    installModeType: OwnNamespace
