
apiVersion: config.mas.ibm.com/v1
kind: SlsCfg
metadata:
  name: max-sls-system
  namespace: mas-max-core
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: max
spec:
  config:
    credentials:
      secretName: sls-registration-key
    url: https://sls.ibm-sls.codehub.dev.fyre.ibm.com
  displayName: SLS (max)
  certificates:
    - alias: sls-ca
      crt: |
          -----BEGIN CERTIFICATE-----
          MIIDwDCCAqigAwIBAgIUaY0bKO6KDiqHI5GQ/1TYnbbYjZAwDQYJKoZIhvcNAQEL
          BQAweDELMAkGA1UEBhMCR0IxDzANBgNVBAcTBkxvbmRvbjEPMA0GA1UECRMGTG9u
          ZG9uMS0wKwYDVQQLEyRJQk0gU3VpdGUgTGljZW5zZSBTZXJ2aWNlIChJbnRlcm5h
          bCkxGDAWBgNVBAMTD3Nscy5zbHMuaWJtLmNvbTAeFw0yNjA5MTUwOTQ5MjBaFw00
          NjA5MTAwOTQ5MjBaMHgxCzAJBgNVBAYTAkdCMQ8wDQYDVQQHEwZMb25kb24xDzAN
          BgNVBAkTBkxvbmRvbjEtMCsGA1UECxMkSUJNIFN1aXRlIExpY2Vuc2UgU2Vydmlj
          ZSAoSW50ZXJuYWwpMRgwFgYDVQQDEw9zbHMuc2xzLmlibS5jb20wggEiMA0GCSqG
          SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDV3/rm2ZckC/wL+vO1EQCFT/Bk+zifyYV5
          MhWn3Jt9+taLgI9Ws7kR/lNnTILewVtgT0RecWHo0eQC7XKJkHkXlLzwcxi3qd2a
          OU//5RMEjYSxSw5rUOLRvqCgKf+AdVN+lGUdJQXWGBZqqydeRc3Cwj1Gv+iNdqXo
          WU2ORCIDd/nUJbF6YKK7nz+NWm0FDgiYKrAsuTp3XP447OZ0MuYFDTd8HdqFLFsL
          t0Jl8MDHQhXpMB0OJph2UEl+WxIOb/MMQn/gxHAIjASOe6hgcRc0TKDdB/fF/k49
          25qNXX4B5KoeHwe3hqvKWyg4W2NvSmWI6FIeLBQ59KvIf+WbKh7rAgMBAAGjQjBA
          MA4GA1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTN4HBD
          tF9T5W5usg6C3x8PRJLkYDANBgkqhkiG9w0BAQsFAAOCAQEASiBFcaKho3oogzFs
          GAKp0Itt2FKENmB6x/f3R6Iq2NAMYnjMsF3EETabVlq1JnOv+2sjo0xeSj+lyYNI
          Hfh9lvFf6aOs4VAun4FNpxp7ePvR65AtUug/yRmp7ciBCCLDRzheSXi2TyIiZSJn
          JlHn0wbGh2sybdFEGoptHKsqQtiEMtl7d8u6PnQ7Cy5CIcshYGjIfUVH3JddI7Lh
          TpplVvO3YNbtb49wy5IhQ42rMBWZdzb8Q6Ir12lzPKTaUlrhOB9YuLX2XP4ltHJb
          WpgApueiKuX4Pk8puGiB2FlIj/oyI2MK6bAOFBh1JVOlNrNFaNrENFJpsSHK8wIQ
          kceBlw==
          -----END CERTIFICATE-----
