
apiVersion: config.mas.ibm.com/v1
kind: SlsCfg
metadata:
  name: max-sls-system
  namespace: mas-max-core
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: max
spec:
  config:
    credentials:
      secretName: sls-registration-key
    url: https://sls.ibm-sls.codehub1.fyre.ibm.com
  displayName: SLS (max)
  certificates:
    - alias: sls-ca
      crt: |
          -----BEGIN CERTIFICATE-----
          MIIDvTCCAqWgAwIBAgIRALu7F3dlnyoivasNQRBQRuIwDQYJKoZIhvcNAQELBQAw
          eDELMAkGA1UEBhMCR0IxDzANBgNVBAcTBkxvbmRvbjEPMA0GA1UECRMGTG9uZG9u
          MS0wKwYDVQQLEyRJQk0gU3VpdGUgTGljZW5zZSBTZXJ2aWNlIChJbnRlcm5hbCkx
          GDAWBgNVBAMTD3Nscy5zbHMuaWJtLmNvbTAeFw0yNjAzMDcwNTI2NTRaFw00NjAz
          MDIwNTI2NTRaMHgxCzAJBgNVBAYTAkdCMQ8wDQYDVQQHEwZMb25kb24xDzANBgNV
          BAkTBkxvbmRvbjEtMCsGA1UECxMkSUJNIFN1aXRlIExpY2Vuc2UgU2VydmljZSAo
          SW50ZXJuYWwpMRgwFgYDVQQDEw9zbHMuc2xzLmlibS5jb20wggEiMA0GCSqGSIb3
          DQEBAQUAA4IBDwAwggEKAoIBAQDMWIPE6GG8vQzEgfL3ICCIBr1xgysjx4uMP6E4
          zHXm59DdibZ3jahJAXMGZTH0N2/hjRgbUbZ4vsBA6xPF3L08uIOKasYQHMzTzCK7
          BV/q/czffcSZoI6gHpUwP1he6asOnCUQbhLxJMeYd418om/laiABAxSlCyrHViIK
          4uN3+yI3o3Z6G3fvX4ATFUT2EpaTN1+WwPVsW69NcifuwoDn/76V8uS+iueX6+ta
          nsHTjyTPFITqrrzHcNptjx4+VeE5xsGsZpf0sJVEOhpLmXaU3AyGp4zhMnAApWES
          0rji75h+F/FeB1XIcWglHS9N3Mf3Fwwh5FcXWzev+s0dqITRAgMBAAGjQjBAMA4G
          A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRLo0D8wF1S
          JIY48QPBPlJ4814kOTANBgkqhkiG9w0BAQsFAAOCAQEAW/V1jHaMCYhNYGQFJVK6
          tnwVVFNbeqVHaw5AY0kk6F7pclS8CZyO/dxnPb8Qa68/WensWmx5gVR8Wk7zEVGl
          mOuEvYtc1kj/V0d0SOnDSPbRk7s1CYF5pUMd7jTlAX+U97BrRUJAPRW6HtaJfjmi
          8L1Jw1LHV4Cg56kgLC6HGCmSz6UHOVHXBfPR79CPuBetO5+UTov3FLf/qOk45/1t
          MZrtJhlvExcXEQB6hhVh2HkcathFhEsmUUxNiYpCQxMu5j2vxz9hRvGZAOo+DsSY
          L2GJ5SHGPYuFdv5OHcHH0ICEiUut1YIPtan//qf4870DnH33Goc515mdiVcB/j2h
          Pg==
          -----END CERTIFICATE-----
