
apiVersion: config.mas.ibm.com/v1
kind: MongoCfg
metadata:
  name: max-mongo-system
  namespace: mas-max-core
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: max
spec:
  config:
    credentials:
      secretName: ibm-mas-mongo-credentials
    hosts:
      - host: codehub.dev.fyre.ibm.com
        port: 27017
    authMechanism: DEFAULT
    configDb: admin
    retryWrites: true
    tlsInsecure: false
  displayName: MongoDb
  certificates:
    - alias: mongodb
      crt: |
          -----BEGIN CERTIFICATE-----
          MIIECTCCAvGgAwIBAgIUGkOZhH6r/HB15yq/V2Sv6e52NUIwDQYJKoZIhvcNAQEL
          BQAwgZMxCzAJBgNVBAYTAklOMQswCQYDVQQIDAJLQTELMAkGA1UEBwwCQkwxETAP
          BgNVBAoMCFBlcnNvbmFsMREwDwYDVQQLDAhQZXJzb25hbDEhMB8GCSqGSIb3DQEJ
          ARYSbWQuamF3YWhhckBpYm0uY29tMSEwHwYDVQQDDBhjb2RlaHViLmRldi5meXJl
          LmlibS5jb20wHhcNMjYwNzI2MDkxNjUwWhcNMzYwNzIzMDkxNjUwWjCBkzELMAkG
          A1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJCTDERMA8GA1UECgwIUGVy
          c29uYWwxETAPBgNVBAsMCFBlcnNvbmFsMSEwHwYJKoZIhvcNAQkBFhJtZC5qYXdh
          aGFyQGlibS5jb20xITAfBgNVBAMMGGNvZGVodWIuZGV2LmZ5cmUuaWJtLmNvbTCC
          ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL3OwNIacKt8TnDnHLpeo9Hm
          NLZCAylltAsB1NavuXvSKLWwiXYd9y1csqKGy8RyoFEwZWmYrejsV8ReDcXSBs/0
          dDjlYjCk6eQCqcuo0nZba3ZqQLyESmi+TwllH0rc8wTzxPjs8jSsF1HyzB0QDAN3
          aSFzRoJ6hkwdJKgq3n7w0DOwraT0q4XnDJnQmsum+kpMAarLFfcbslPw2Tdvjg34
          0uu5z1vFXUpVrUtGrf210KwcqhXORJhlbe6MLk8a2U0Ct8vqBxyQLWtX0Z923/Fu
          Ninmku+W4uSv//BIzS1BQUe9k8ukz6mRt9Tjrho/xrF+QopaZQV1NqwdHo08UtEC
          AwEAAaNTMFEwHQYDVR0OBBYEFJSUaE1sY8p34Qq5DTfrsFp0skIwMB8GA1UdIwQY
          MBaAFJSUaE1sY8p34Qq5DTfrsFp0skIwMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
          hvcNAQELBQADggEBAG/J68JeLEDmi8/PIcjHIoEE+B+Xi66Rz7rtnGXBHx5zqEZ/
          iDgX6TRIC7CUIiOUZFRMHAj5h1uZIPWf4PR1sQhXuN4ndT7R2DLUuIQ+EIUw2UJK
          E5kw+QmDMlsuIthVBPF2gGkoFTrYg9PTiun4UEWOBqrKonXD/GoYj99sTlMHH1Lk
          M7u94N09gl4xiXM4U8XD6OWjvmlxS7SJQrDRR39wBc6EDg4QfDPZfFWykkKDqQuK
          VsnHjDYgx3Lt0MmRR5iIC0FvA7LRicAO/KK9Orl/T5rVgTe4UaISrOLz4uRXkTz5
          F5ENrIsTYpQVGCrUZLDijuCUyINHvm2+xyfybi4=
          -----END CERTIFICATE-----
