apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  description: Online Catalog Source for IBM Maximo Application Suite
  displayName: IBM Maximo Operators (v9-251231-amd64)
  image: 'icr.io/cpopen/ibm-maximo-operator-catalog:v9-251231-amd64'
  priority: 90
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m

