apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-data-reporter-operator
  namespace: ibm-software-central
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ibm-data-reporter-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-data-reporter-operator.v2.23.1
